// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/ecodeclub/webook/internal/cases"
	"github.com/ecodeclub/webook/internal/search"
	"github.com/ecodeclub/webook/internal/search/internal/web"
	testioc "github.com/ecodeclub/webook/internal/test/ioc"
)

// Injectors from wire.go:

func InitHandler(caModule *cases.Module) (*web.Handler, error) {
	client := testioc.InitES()
	mq := testioc.InitMQ()
	module, err := search.InitModule(client, mq, caModule)
	if err != nil {
		return nil, err
	}
	handler := module.Hdl
	return handler, nil
}
