// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/ecodeclub/webook/internal/label"
	"github.com/ecodeclub/webook/internal/label/internal/web"
	testioc "github.com/ecodeclub/webook/internal/test/ioc"
)

// Injectors from wire.go:

func InitHandler() (*web.Handler, error) {
	db := testioc.InitDB()
	handler := label.InitHandler(db)
	return handler, nil
}
