// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package resume

import (
	"github.com/ecodeclub/webook/internal/cases"
	"github.com/ecodeclub/webook/internal/resume/internal/repository"
	"github.com/ecodeclub/webook/internal/resume/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/resume/internal/service"
	"github.com/ecodeclub/webook/internal/resume/internal/web"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB, caModule *cases.Module) *Module {
	resumeProjectDAO := dao.NewResumeProjectDAO(db)
	resumeProjectRepo := repository.NewResumeProjectRepo(resumeProjectDAO)
	serviceService := service.NewService(resumeProjectRepo)
	examineService := caModule.ExamineSvc
	handler := web.NewHandler(serviceService, examineService)
	module := &Module{
		Hdl: handler,
	}
	return module
}
