// Code generated by MockGen. DO NOT EDIT.
// Source: ./gpt.go
//
// Generated by this command:
//
//	mockgen -source=./gpt.go -destination=../../mocks/gpt.mock.go -package=aimocks -typed=true GPTService
//

// Package aimocks is a generated GoMock package.
package aimocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ecodeclub/webook/internal/ai/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGPTService is a mock of GPTService interface.
type MockGPTService struct {
	ctrl     *gomock.Controller
	recorder *MockGPTServiceMockRecorder
}

// MockGPTServiceMockRecorder is the mock recorder for MockGPTService.
type MockGPTServiceMockRecorder struct {
	mock *MockGPTService
}

// NewMockGPTService creates a new mock instance.
func NewMockGPTService(ctrl *gomock.Controller) *MockGPTService {
	mock := &MockGPTService{ctrl: ctrl}
	mock.recorder = &MockGPTServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPTService) EXPECT() *MockGPTServiceMockRecorder {
	return m.recorder
}

// Invoke mocks base method.
func (m *MockGPTService) Invoke(ctx context.Context, req domain.GPTRequest) (domain.GPTResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", ctx, req)
	ret0, _ := ret[0].(domain.GPTResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockGPTServiceMockRecorder) Invoke(ctx, req any) *MockGPTServiceInvokeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockGPTService)(nil).Invoke), ctx, req)
	return &MockGPTServiceInvokeCall{Call: call}
}

// MockGPTServiceInvokeCall wrap *gomock.Call
type MockGPTServiceInvokeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGPTServiceInvokeCall) Return(arg0 domain.GPTResponse, arg1 error) *MockGPTServiceInvokeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGPTServiceInvokeCall) Do(f func(context.Context, domain.GPTRequest) (domain.GPTResponse, error)) *MockGPTServiceInvokeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGPTServiceInvokeCall) DoAndReturn(f func(context.Context, domain.GPTRequest) (domain.GPTResponse, error)) *MockGPTServiceInvokeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
