// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bff

import (
	"github.com/ecodeclub/webook/internal/bff/internal/web"
	service2 "github.com/ecodeclub/webook/internal/cases/internal/service"
	"github.com/ecodeclub/webook/internal/interactive/internal/service"
	service3 "github.com/ecodeclub/webook/internal/question/internal/service"
)

// Injectors from wire.go:

func InitHandler(intrSvc service.Service, caseSvc service2.Service, queSvc service3.Service, queSetSvc service3.QuestionSetService, examSvc service3.ExamineService) (*web.Handler, error) {
	handler := web.NewHandler(intrSvc, caseSvc, queSvc, queSetSvc, examSvc)
	return handler, nil
}

// wire.go:

type Hdl web.Handler
