version: '3.8'

services:
  browserless:
    image: browserless/chrome:latest
    container_name: browserless-chrome
    ports:
      - "3000:3000"  # 默认API端口
      - "9222:9222"  # CDP调试端口
    environment:
      # 基础配置
      - MAX_CONCURRENT_SESSIONS=10  # 最大并发会话数
      - CONNECTION_TIMEOUT=60000    # 连接超时(毫秒)
      - MAX_QUEUE_LENGTH=10         # 最大排队长度
      - ENABLE_DEBUGGER=true        # 启用调试器
      - CHROME_REFRESH_TIME=3600000 # Chrome实例刷新时间(毫秒)
      
      # 安全配置
      - TOKEN=  # 禁用TOKEN认证，设置为空字符串
      # - ENABLE_CORS=true            # 启用CORS(默认启用)
      # - CORS_ORIGIN=*               # CORS源
      
      # 性能调优
      - CHROME_EXTRA_LAUNCH_ARGS=--no-sandbox --disable-dev-shm-usage --disable-gpu
      - PREBOOT_CHROME=true           # 预启动Chrome
      - KEEP_ALIVE=true               # 保持Chrome实例存活
      - WORKSPACE_DELETE_EXPIRED=true # 删除过期的工作区
      - WORKSPACE_EXPIRE_DAYS=7       # 工作区过期天数
      
      # 资源限制
      - CPU_LIMIT=1                   # CPU限制(核心数)
      - MEMORY_LIMIT=2048             # 内存限制(MB)
      
      # 功能开关
      - ENABLE_PDF_ENDPOINT=true      # 启用PDF生成端点
      - ENABLE_DEBUGGER=true          # 启用调试器
      - ENABLE_METRICS=true           # 启用指标收集
      
      # 日志配置
      - LOG_LEVEL=info                # 日志级别(debug|info|warn|error)
      - PRINT_CHROME_LOGS=true        # 打印Chrome日志
    volumes:
      - ./data/browserless:/workspace # 持久化工作区
    restart: unless-stopped
    shm_size: 2gb                     # 增加共享内存大小，避免崩溃
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
