// Code generated by MockGen. DO NOT EDIT.
// Source: ./case_set.go
//
// Generated by this command:
//
//	mockgen -source=./case_set.go -destination=../../mocks/case_set.mock.go -package=casemocks -typed CaseSetService
//

// Package casemocks is a generated GoMock package.
package casemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ecodeclub/webook/internal/cases/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCaseSetService is a mock of CaseSetService interface.
type MockCaseSetService struct {
	ctrl     *gomock.Controller
	recorder *MockCaseSetServiceMockRecorder
}

// MockCaseSetServiceMockRecorder is the mock recorder for MockCaseSetService.
type MockCaseSetServiceMockRecorder struct {
	mock *MockCaseSetService
}

// NewMockCaseSetService creates a new mock instance.
func NewMockCaseSetService(ctrl *gomock.Controller) *MockCaseSetService {
	mock := &MockCaseSetService{ctrl: ctrl}
	mock.recorder = &MockCaseSetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaseSetService) EXPECT() *MockCaseSetServiceMockRecorder {
	return m.recorder
}

// Detail mocks base method.
func (m *MockCaseSetService) Detail(ctx context.Context, id int64) (domain.CaseSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, id)
	ret0, _ := ret[0].(domain.CaseSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockCaseSetServiceMockRecorder) Detail(ctx, id any) *MockCaseSetServiceDetailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockCaseSetService)(nil).Detail), ctx, id)
	return &MockCaseSetServiceDetailCall{Call: call}
}

// MockCaseSetServiceDetailCall wrap *gomock.Call
type MockCaseSetServiceDetailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCaseSetServiceDetailCall) Return(arg0 domain.CaseSet, arg1 error) *MockCaseSetServiceDetailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCaseSetServiceDetailCall) Do(f func(context.Context, int64) (domain.CaseSet, error)) *MockCaseSetServiceDetailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCaseSetServiceDetailCall) DoAndReturn(f func(context.Context, int64) (domain.CaseSet, error)) *MockCaseSetServiceDetailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByBiz mocks base method.
func (m *MockCaseSetService) GetByBiz(ctx context.Context, biz string, bizId int64) (domain.CaseSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBiz", ctx, biz, bizId)
	ret0, _ := ret[0].(domain.CaseSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBiz indicates an expected call of GetByBiz.
func (mr *MockCaseSetServiceMockRecorder) GetByBiz(ctx, biz, bizId any) *MockCaseSetServiceGetByBizCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBiz", reflect.TypeOf((*MockCaseSetService)(nil).GetByBiz), ctx, biz, bizId)
	return &MockCaseSetServiceGetByBizCall{Call: call}
}

// MockCaseSetServiceGetByBizCall wrap *gomock.Call
type MockCaseSetServiceGetByBizCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCaseSetServiceGetByBizCall) Return(arg0 domain.CaseSet, arg1 error) *MockCaseSetServiceGetByBizCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCaseSetServiceGetByBizCall) Do(f func(context.Context, string, int64) (domain.CaseSet, error)) *MockCaseSetServiceGetByBizCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCaseSetServiceGetByBizCall) DoAndReturn(f func(context.Context, string, int64) (domain.CaseSet, error)) *MockCaseSetServiceGetByBizCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByIds mocks base method.
func (m *MockCaseSetService) GetByIds(ctx context.Context, ids []int64) ([]domain.CaseSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.CaseSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockCaseSetServiceMockRecorder) GetByIds(ctx, ids any) *MockCaseSetServiceGetByIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockCaseSetService)(nil).GetByIds), ctx, ids)
	return &MockCaseSetServiceGetByIdsCall{Call: call}
}

// MockCaseSetServiceGetByIdsCall wrap *gomock.Call
type MockCaseSetServiceGetByIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCaseSetServiceGetByIdsCall) Return(arg0 []domain.CaseSet, arg1 error) *MockCaseSetServiceGetByIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCaseSetServiceGetByIdsCall) Do(f func(context.Context, []int64) ([]domain.CaseSet, error)) *MockCaseSetServiceGetByIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCaseSetServiceGetByIdsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.CaseSet, error)) *MockCaseSetServiceGetByIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByIdsWithCases mocks base method.
func (m *MockCaseSetService) GetByIdsWithCases(ctx context.Context, ids []int64) ([]domain.CaseSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdsWithCases", ctx, ids)
	ret0, _ := ret[0].([]domain.CaseSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdsWithCases indicates an expected call of GetByIdsWithCases.
func (mr *MockCaseSetServiceMockRecorder) GetByIdsWithCases(ctx, ids any) *MockCaseSetServiceGetByIdsWithCasesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdsWithCases", reflect.TypeOf((*MockCaseSetService)(nil).GetByIdsWithCases), ctx, ids)
	return &MockCaseSetServiceGetByIdsWithCasesCall{Call: call}
}

// MockCaseSetServiceGetByIdsWithCasesCall wrap *gomock.Call
type MockCaseSetServiceGetByIdsWithCasesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCaseSetServiceGetByIdsWithCasesCall) Return(arg0 []domain.CaseSet, arg1 error) *MockCaseSetServiceGetByIdsWithCasesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCaseSetServiceGetByIdsWithCasesCall) Do(f func(context.Context, []int64) ([]domain.CaseSet, error)) *MockCaseSetServiceGetByIdsWithCasesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCaseSetServiceGetByIdsWithCasesCall) DoAndReturn(f func(context.Context, []int64) ([]domain.CaseSet, error)) *MockCaseSetServiceGetByIdsWithCasesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCandidates mocks base method.
func (m *MockCaseSetService) GetCandidates(ctx context.Context, id int64, offset, limit int) ([]domain.Case, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCandidates", ctx, id, offset, limit)
	ret0, _ := ret[0].([]domain.Case)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCandidates indicates an expected call of GetCandidates.
func (mr *MockCaseSetServiceMockRecorder) GetCandidates(ctx, id, offset, limit any) *MockCaseSetServiceGetCandidatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCandidates", reflect.TypeOf((*MockCaseSetService)(nil).GetCandidates), ctx, id, offset, limit)
	return &MockCaseSetServiceGetCandidatesCall{Call: call}
}

// MockCaseSetServiceGetCandidatesCall wrap *gomock.Call
type MockCaseSetServiceGetCandidatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCaseSetServiceGetCandidatesCall) Return(arg0 []domain.Case, arg1 int64, arg2 error) *MockCaseSetServiceGetCandidatesCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCaseSetServiceGetCandidatesCall) Do(f func(context.Context, int64, int, int) ([]domain.Case, int64, error)) *MockCaseSetServiceGetCandidatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCaseSetServiceGetCandidatesCall) DoAndReturn(f func(context.Context, int64, int, int) ([]domain.Case, int64, error)) *MockCaseSetServiceGetCandidatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockCaseSetService) List(ctx context.Context, offset, limit int) ([]domain.CaseSet, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.CaseSet)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockCaseSetServiceMockRecorder) List(ctx, offset, limit any) *MockCaseSetServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCaseSetService)(nil).List), ctx, offset, limit)
	return &MockCaseSetServiceListCall{Call: call}
}

// MockCaseSetServiceListCall wrap *gomock.Call
type MockCaseSetServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCaseSetServiceListCall) Return(arg0 []domain.CaseSet, arg1 int64, arg2 error) *MockCaseSetServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCaseSetServiceListCall) Do(f func(context.Context, int, int) ([]domain.CaseSet, int64, error)) *MockCaseSetServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCaseSetServiceListCall) DoAndReturn(f func(context.Context, int, int) ([]domain.CaseSet, int64, error)) *MockCaseSetServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByBiz mocks base method.
func (m *MockCaseSetService) ListByBiz(ctx context.Context, offset, limit int, biz string) ([]domain.CaseSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByBiz", ctx, offset, limit, biz)
	ret0, _ := ret[0].([]domain.CaseSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByBiz indicates an expected call of ListByBiz.
func (mr *MockCaseSetServiceMockRecorder) ListByBiz(ctx, offset, limit, biz any) *MockCaseSetServiceListByBizCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByBiz", reflect.TypeOf((*MockCaseSetService)(nil).ListByBiz), ctx, offset, limit, biz)
	return &MockCaseSetServiceListByBizCall{Call: call}
}

// MockCaseSetServiceListByBizCall wrap *gomock.Call
type MockCaseSetServiceListByBizCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCaseSetServiceListByBizCall) Return(arg0 []domain.CaseSet, arg1 error) *MockCaseSetServiceListByBizCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCaseSetServiceListByBizCall) Do(f func(context.Context, int, int, string) ([]domain.CaseSet, error)) *MockCaseSetServiceListByBizCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCaseSetServiceListByBizCall) DoAndReturn(f func(context.Context, int, int, string) ([]domain.CaseSet, error)) *MockCaseSetServiceListByBizCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDefault mocks base method.
func (m *MockCaseSetService) ListDefault(ctx context.Context, offset, limit int) (int64, []domain.CaseSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDefault", ctx, offset, limit)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]domain.CaseSet)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDefault indicates an expected call of ListDefault.
func (mr *MockCaseSetServiceMockRecorder) ListDefault(ctx, offset, limit any) *MockCaseSetServiceListDefaultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDefault", reflect.TypeOf((*MockCaseSetService)(nil).ListDefault), ctx, offset, limit)
	return &MockCaseSetServiceListDefaultCall{Call: call}
}

// MockCaseSetServiceListDefaultCall wrap *gomock.Call
type MockCaseSetServiceListDefaultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCaseSetServiceListDefaultCall) Return(arg0 int64, arg1 []domain.CaseSet, arg2 error) *MockCaseSetServiceListDefaultCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCaseSetServiceListDefaultCall) Do(f func(context.Context, int, int) (int64, []domain.CaseSet, error)) *MockCaseSetServiceListDefaultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCaseSetServiceListDefaultCall) DoAndReturn(f func(context.Context, int, int) (int64, []domain.CaseSet, error)) *MockCaseSetServiceListDefaultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockCaseSetService) Save(ctx context.Context, set domain.CaseSet) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, set)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockCaseSetServiceMockRecorder) Save(ctx, set any) *MockCaseSetServiceSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCaseSetService)(nil).Save), ctx, set)
	return &MockCaseSetServiceSaveCall{Call: call}
}

// MockCaseSetServiceSaveCall wrap *gomock.Call
type MockCaseSetServiceSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCaseSetServiceSaveCall) Return(arg0 int64, arg1 error) *MockCaseSetServiceSaveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCaseSetServiceSaveCall) Do(f func(context.Context, domain.CaseSet) (int64, error)) *MockCaseSetServiceSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCaseSetServiceSaveCall) DoAndReturn(f func(context.Context, domain.CaseSet) (int64, error)) *MockCaseSetServiceSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateCases mocks base method.
func (m *MockCaseSetService) UpdateCases(ctx context.Context, set domain.CaseSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCases", ctx, set)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCases indicates an expected call of UpdateCases.
func (mr *MockCaseSetServiceMockRecorder) UpdateCases(ctx, set any) *MockCaseSetServiceUpdateCasesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCases", reflect.TypeOf((*MockCaseSetService)(nil).UpdateCases), ctx, set)
	return &MockCaseSetServiceUpdateCasesCall{Call: call}
}

// MockCaseSetServiceUpdateCasesCall wrap *gomock.Call
type MockCaseSetServiceUpdateCasesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCaseSetServiceUpdateCasesCall) Return(arg0 error) *MockCaseSetServiceUpdateCasesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCaseSetServiceUpdateCasesCall) Do(f func(context.Context, domain.CaseSet) error) *MockCaseSetServiceUpdateCasesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCaseSetServiceUpdateCasesCall) DoAndReturn(f func(context.Context, domain.CaseSet) error) *MockCaseSetServiceUpdateCasesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
