// Code generated by MockGen. DO NOT EDIT.
// Source: ./examine.go
//
// Generated by this command:
//
//	mockgen -source=./examine.go -destination=../../mocks/examine.mock.go -package=casemocks -typed=true ExamineService
//

// Package casemocks is a generated GoMock package.
package casemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ecodeclub/webook/internal/cases/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockExamineService is a mock of ExamineService interface.
type MockExamineService struct {
	ctrl     *gomock.Controller
	recorder *MockExamineServiceMockRecorder
}

// MockExamineServiceMockRecorder is the mock recorder for MockExamineService.
type MockExamineServiceMockRecorder struct {
	mock *MockExamineService
}

// NewMockExamineService creates a new mock instance.
func NewMockExamineService(ctrl *gomock.Controller) *MockExamineService {
	mock := &MockExamineService{ctrl: ctrl}
	mock.recorder = &MockExamineServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExamineService) EXPECT() *MockExamineServiceMockRecorder {
	return m.recorder
}

// Examine mocks base method.
func (m *MockExamineService) Examine(ctx context.Context, uid, cid int64, input string) (domain.ExamineCaseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Examine", ctx, uid, cid, input)
	ret0, _ := ret[0].(domain.ExamineCaseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Examine indicates an expected call of Examine.
func (mr *MockExamineServiceMockRecorder) Examine(ctx, uid, cid, input any) *MockExamineServiceExamineCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Examine", reflect.TypeOf((*MockExamineService)(nil).Examine), ctx, uid, cid, input)
	return &MockExamineServiceExamineCall{Call: call}
}

// MockExamineServiceExamineCall wrap *gomock.Call
type MockExamineServiceExamineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExamineServiceExamineCall) Return(arg0 domain.ExamineCaseResult, arg1 error) *MockExamineServiceExamineCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExamineServiceExamineCall) Do(f func(context.Context, int64, int64, string) (domain.ExamineCaseResult, error)) *MockExamineServiceExamineCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExamineServiceExamineCall) DoAndReturn(f func(context.Context, int64, int64, string) (domain.ExamineCaseResult, error)) *MockExamineServiceExamineCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetResults mocks base method.
func (m *MockExamineService) GetResults(ctx context.Context, uid int64, ids []int64) (map[int64]domain.ExamineCaseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResults", ctx, uid, ids)
	ret0, _ := ret[0].(map[int64]domain.ExamineCaseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResults indicates an expected call of GetResults.
func (mr *MockExamineServiceMockRecorder) GetResults(ctx, uid, ids any) *MockExamineServiceGetResultsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResults", reflect.TypeOf((*MockExamineService)(nil).GetResults), ctx, uid, ids)
	return &MockExamineServiceGetResultsCall{Call: call}
}

// MockExamineServiceGetResultsCall wrap *gomock.Call
type MockExamineServiceGetResultsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExamineServiceGetResultsCall) Return(arg0 map[int64]domain.ExamineCaseResult, arg1 error) *MockExamineServiceGetResultsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExamineServiceGetResultsCall) Do(f func(context.Context, int64, []int64) (map[int64]domain.ExamineCaseResult, error)) *MockExamineServiceGetResultsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExamineServiceGetResultsCall) DoAndReturn(f func(context.Context, int64, []int64) (map[int64]domain.ExamineCaseResult, error)) *MockExamineServiceGetResultsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QuestionResult mocks base method.
func (m *MockExamineService) QuestionResult(ctx context.Context, uid, cid int64) (domain.CaseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuestionResult", ctx, uid, cid)
	ret0, _ := ret[0].(domain.CaseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuestionResult indicates an expected call of QuestionResult.
func (mr *MockExamineServiceMockRecorder) QuestionResult(ctx, uid, cid any) *MockExamineServiceQuestionResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuestionResult", reflect.TypeOf((*MockExamineService)(nil).QuestionResult), ctx, uid, cid)
	return &MockExamineServiceQuestionResultCall{Call: call}
}

// MockExamineServiceQuestionResultCall wrap *gomock.Call
type MockExamineServiceQuestionResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExamineServiceQuestionResultCall) Return(arg0 domain.CaseResult, arg1 error) *MockExamineServiceQuestionResultCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExamineServiceQuestionResultCall) Do(f func(context.Context, int64, int64) (domain.CaseResult, error)) *MockExamineServiceQuestionResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExamineServiceQuestionResultCall) DoAndReturn(f func(context.Context, int64, int64) (domain.CaseResult, error)) *MockExamineServiceQuestionResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
