// Code generated by MockGen. DO NOT EDIT.
// Source: ./user.go
//
// Generated by this command:
//
//	mockgen -source=./user.go -package=usermocks -typed=true -destination=../../mocks/user.mock.go UserService
//
// Package usermocks is a generated GoMock package.
package usermocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ecodeclub/webook/internal/user/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// FindOrCreateByWechat mocks base method.
func (m *MockUserService) FindOrCreateByWechat(ctx context.Context, info domain.WechatInfo) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateByWechat", ctx, info)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateByWechat indicates an expected call of FindOrCreateByWechat.
func (mr *MockUserServiceMockRecorder) FindOrCreateByWechat(ctx, info any) *UserServiceFindOrCreateByWechatCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateByWechat", reflect.TypeOf((*MockUserService)(nil).FindOrCreateByWechat), ctx, info)
	return &UserServiceFindOrCreateByWechatCall{Call: call}
}

// UserServiceFindOrCreateByWechatCall wrap *gomock.Call
type UserServiceFindOrCreateByWechatCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UserServiceFindOrCreateByWechatCall) Return(arg0 domain.User, arg1 error) *UserServiceFindOrCreateByWechatCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UserServiceFindOrCreateByWechatCall) Do(f func(context.Context, domain.WechatInfo) (domain.User, error)) *UserServiceFindOrCreateByWechatCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UserServiceFindOrCreateByWechatCall) DoAndReturn(f func(context.Context, domain.WechatInfo) (domain.User, error)) *UserServiceFindOrCreateByWechatCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Profile mocks base method.
func (m *MockUserService) Profile(ctx context.Context, id int64) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Profile indicates an expected call of Profile.
func (mr *MockUserServiceMockRecorder) Profile(ctx, id any) *UserServiceProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockUserService)(nil).Profile), ctx, id)
	return &UserServiceProfileCall{Call: call}
}

// UserServiceProfileCall wrap *gomock.Call
type UserServiceProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UserServiceProfileCall) Return(arg0 domain.User, arg1 error) *UserServiceProfileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UserServiceProfileCall) Do(f func(context.Context, int64) (domain.User, error)) *UserServiceProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UserServiceProfileCall) DoAndReturn(f func(context.Context, int64) (domain.User, error)) *UserServiceProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateNonSensitiveInfo mocks base method.
func (m *MockUserService) UpdateNonSensitiveInfo(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNonSensitiveInfo", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNonSensitiveInfo indicates an expected call of UpdateNonSensitiveInfo.
func (mr *MockUserServiceMockRecorder) UpdateNonSensitiveInfo(ctx, user any) *UserServiceUpdateNonSensitiveInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNonSensitiveInfo", reflect.TypeOf((*MockUserService)(nil).UpdateNonSensitiveInfo), ctx, user)
	return &UserServiceUpdateNonSensitiveInfoCall{Call: call}
}

// UserServiceUpdateNonSensitiveInfoCall wrap *gomock.Call
type UserServiceUpdateNonSensitiveInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *UserServiceUpdateNonSensitiveInfoCall) Return(arg0 error) *UserServiceUpdateNonSensitiveInfoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *UserServiceUpdateNonSensitiveInfoCall) Do(f func(context.Context, domain.User) error) *UserServiceUpdateNonSensitiveInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *UserServiceUpdateNonSensitiveInfoCall) DoAndReturn(f func(context.Context, domain.User) error) *UserServiceUpdateNonSensitiveInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
