// Code generated by MockGen. DO NOT EDIT.
// Source: ./type.go
//
// Generated by this command:
//
//	mockgen -source=./type.go -destination=./stream_mocks/stream_handler.mock.go -package=hdlmocks -typed=true StreamHandler
//

// Package hdlmocks is a generated GoMock package.
package hdlmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ecodeclub/webook/internal/ai/internal/domain"
	handler "github.com/ecodeclub/webook/internal/ai/internal/service/llm/handler"
	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockHandler) Handle(ctx context.Context, req domain.LLMRequest) (domain.LLMResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(domain.LLMResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockHandlerMockRecorder) Handle(ctx, req any) *MockHandlerHandleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockHandler)(nil).Handle), ctx, req)
	return &MockHandlerHandleCall{Call: call}
}

// MockHandlerHandleCall wrap *gomock.Call
type MockHandlerHandleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlerHandleCall) Return(arg0 domain.LLMResponse, arg1 error) *MockHandlerHandleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlerHandleCall) Do(f func(context.Context, domain.LLMRequest) (domain.LLMResponse, error)) *MockHandlerHandleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlerHandleCall) DoAndReturn(f func(context.Context, domain.LLMRequest) (domain.LLMResponse, error)) *MockHandlerHandleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBuilder is a mock of Builder interface.
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderMockRecorder
	isgomock struct{}
}

// MockBuilderMockRecorder is the mock recorder for MockBuilder.
type MockBuilderMockRecorder struct {
	mock *MockBuilder
}

// NewMockBuilder creates a new mock instance.
func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder {
	mock := &MockBuilder{ctrl: ctrl}
	mock.recorder = &MockBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilder) EXPECT() *MockBuilderMockRecorder {
	return m.recorder
}

// Next mocks base method.
func (m *MockBuilder) Next(next handler.Handler) handler.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", next)
	ret0, _ := ret[0].(handler.Handler)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockBuilderMockRecorder) Next(next any) *MockBuilderNextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockBuilder)(nil).Next), next)
	return &MockBuilderNextCall{Call: call}
}

// MockBuilderNextCall wrap *gomock.Call
type MockBuilderNextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBuilderNextCall) Return(arg0 handler.Handler) *MockBuilderNextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBuilderNextCall) Do(f func(handler.Handler) handler.Handler) *MockBuilderNextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBuilderNextCall) DoAndReturn(f func(handler.Handler) handler.Handler) *MockBuilderNextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStreamHandler is a mock of StreamHandler interface.
type MockStreamHandler struct {
	ctrl     *gomock.Controller
	recorder *MockStreamHandlerMockRecorder
	isgomock struct{}
}

// MockStreamHandlerMockRecorder is the mock recorder for MockStreamHandler.
type MockStreamHandlerMockRecorder struct {
	mock *MockStreamHandler
}

// NewMockStreamHandler creates a new mock instance.
func NewMockStreamHandler(ctrl *gomock.Controller) *MockStreamHandler {
	mock := &MockStreamHandler{ctrl: ctrl}
	mock.recorder = &MockStreamHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamHandler) EXPECT() *MockStreamHandlerMockRecorder {
	return m.recorder
}

// StreamHandle mocks base method.
func (m *MockStreamHandler) StreamHandle(ctx context.Context, req domain.LLMRequest) (chan domain.StreamEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamHandle", ctx, req)
	ret0, _ := ret[0].(chan domain.StreamEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamHandle indicates an expected call of StreamHandle.
func (mr *MockStreamHandlerMockRecorder) StreamHandle(ctx, req any) *MockStreamHandlerStreamHandleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamHandle", reflect.TypeOf((*MockStreamHandler)(nil).StreamHandle), ctx, req)
	return &MockStreamHandlerStreamHandleCall{Call: call}
}

// MockStreamHandlerStreamHandleCall wrap *gomock.Call
type MockStreamHandlerStreamHandleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStreamHandlerStreamHandleCall) Return(arg0 chan domain.StreamEvent, arg1 error) *MockStreamHandlerStreamHandleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStreamHandlerStreamHandleCall) Do(f func(context.Context, domain.LLMRequest) (chan domain.StreamEvent, error)) *MockStreamHandlerStreamHandleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStreamHandlerStreamHandleCall) DoAndReturn(f func(context.Context, domain.LLMRequest) (chan domain.StreamEvent, error)) *MockStreamHandlerStreamHandleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
