// Code generated by MockGen. DO NOT EDIT.
// Source: ./producer.go
//
// Generated by this command:
//
//	mockgen -source=./producer.go -package=evtmocks -destination=./mocks/producer.mock.go -typed OrderEventProducer
//
// Package evtmocks is a generated GoMock package.
package evtmocks

import (
	context "context"
	reflect "reflect"

	event "github.com/ecodeclub/webook/internal/order/internal/event"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderEventProducer is a mock of OrderEventProducer interface.
type MockOrderEventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockOrderEventProducerMockRecorder
}

// MockOrderEventProducerMockRecorder is the mock recorder for MockOrderEventProducer.
type MockOrderEventProducerMockRecorder struct {
	mock *MockOrderEventProducer
}

// NewMockOrderEventProducer creates a new mock instance.
func NewMockOrderEventProducer(ctrl *gomock.Controller) *MockOrderEventProducer {
	mock := &MockOrderEventProducer{ctrl: ctrl}
	mock.recorder = &MockOrderEventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderEventProducer) EXPECT() *MockOrderEventProducerMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockOrderEventProducer) Produce(ctx context.Context, evt event.OrderEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockOrderEventProducerMockRecorder) Produce(ctx, evt any) *OrderEventProducerProduceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockOrderEventProducer)(nil).Produce), ctx, evt)
	return &OrderEventProducerProduceCall{Call: call}
}

// OrderEventProducerProduceCall wrap *gomock.Call
type OrderEventProducerProduceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *OrderEventProducerProduceCall) Return(arg0 error) *OrderEventProducerProduceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *OrderEventProducerProduceCall) Do(f func(context.Context, event.OrderEvent) error) *OrderEventProducerProduceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *OrderEventProducerProduceCall) DoAndReturn(f func(context.Context, event.OrderEvent) error) *OrderEventProducerProduceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
