// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/ecodeclub/webook/internal/ai"
	"github.com/ecodeclub/webook/internal/cases"
	"github.com/ecodeclub/webook/internal/cases/internal/event"
	"github.com/ecodeclub/webook/internal/cases/internal/repository"
	"github.com/ecodeclub/webook/internal/cases/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/cases/internal/service"
	"github.com/ecodeclub/webook/internal/cases/internal/web"
	"github.com/ecodeclub/webook/internal/interactive"
	testioc "github.com/ecodeclub/webook/internal/test/ioc"
)

// Injectors from wire.go:

func InitModule(syncProducer event.SyncEventProducer, intrModule *interactive.Module) (*cases.Module, error) {
	db := testioc.InitDB()
	caseDAO := cases.InitCaseDAO(db)
	caseRepo := repository.NewCaseRepo(caseDAO)
	mq := testioc.InitMQ()
	interactiveEventProducer, err := event.NewInteractiveEventProducer(mq)
	if err != nil {
		return nil, err
	}
	serviceService := service.NewService(caseRepo, interactiveEventProducer, syncProducer)
	service2 := intrModule.Svc
	handler := web.NewHandler(serviceService, service2)
	caseSetDAO := dao.NewCaseSetDAO(db)
	caseSetRepository := repository.NewCaseSetRepo(caseSetDAO)
	caseSetService := service.NewCaseSetService(caseSetRepository, caseRepo, interactiveEventProducer)
	adminCaseSetHandler := web.NewAdminCaseSetHandler(caseSetService)
	module := &cases.Module{
		Svc:             serviceService,
		Hdl:             handler,
		AdminSetHandler: adminCaseSetHandler,
	}
	return module, nil
}

func InitExamModule(syncProducer event.SyncEventProducer, intrModule *interactive.Module, aiModule *ai.Module) (*cases.Module, error) {
	db := testioc.InitDB()
	caseDAO := cases.InitCaseDAO(db)
	caseRepo := repository.NewCaseRepo(caseDAO)
	mq := testioc.InitMQ()
	interactiveEventProducer, err := event.NewInteractiveEventProducer(mq)
	if err != nil {
		return nil, err
	}
	serviceService := service.NewService(caseRepo, interactiveEventProducer, syncProducer)
	caseSetDAO := dao.NewCaseSetDAO(db)
	caseSetRepository := repository.NewCaseSetRepo(caseSetDAO)
	caseSetService := service.NewCaseSetService(caseSetRepository, caseRepo, interactiveEventProducer)
	service2 := intrModule.Svc
	handler := web.NewHandler(serviceService, service2)
	adminCaseSetHandler := web.NewAdminCaseSetHandler(caseSetService)
	examineDAO := dao.NewGORMExamineDAO(db)
	examineRepository := repository.NewCachedExamineRepository(examineDAO)
	llmService := aiModule.Svc
	examineService := service.NewLLMExamineService(caseRepo, examineRepository, llmService)
	examineHandler := web.NewExamineHandler(examineService)
	caseSetHandler := web.NewCaseSetHandler(caseSetService, examineService, service2)
	module := &cases.Module{
		Svc:             serviceService,
		SetSvc:          caseSetService,
		Hdl:             handler,
		AdminSetHandler: adminCaseSetHandler,
		ExamineHdl:      examineHandler,
		CsHdl:           caseSetHandler,
	}
	return module, nil
}
