// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/ecodeclub/webook/internal/company"
	testioc "github.com/ecodeclub/webook/internal/test/ioc"
)

// Injectors from wire.go:

func InitModule() (*company.Module, error) {
	v := testioc.InitDB()
	module, err := company.InitModule(v)
	if err != nil {
		return nil, err
	}
	return module, nil
}
