// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/ecodeclub/webook/internal/interactive"
	"github.com/ecodeclub/webook/internal/project"
	testioc "github.com/ecodeclub/webook/internal/test/ioc"
)

// Injectors from wire.go:

func InitModule(intrModule *interactive.Module) (*project.Module, error) {
	db := testioc.InitDB()
	mq := testioc.InitMQ()
	module, err := project.InitModule(db, intrModule, mq)
	if err != nil {
		return nil, err
	}
	return module, nil
}
