// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"context"
	"sync"

	"github.com/ecodeclub/mq-api"
	"github.com/ecodeclub/webook/internal/product/internal/domain"
	"github.com/ecodeclub/webook/internal/product/internal/event"
	"github.com/ecodeclub/webook/internal/product/internal/repository"
	"github.com/ecodeclub/webook/internal/product/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/product/internal/service"
	"github.com/ecodeclub/webook/internal/product/internal/web"
	"github.com/ego-component/egorm"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB, cmq mq.MQ) (*Module, error) {
	service := InitService(db)
	handler := web.NewHandler(service)
	productConsumer := InitConsumer(service, cmq)
	module := &Module{
		Hdl:      handler,
		Consumer: productConsumer,
		Svc:      service,
	}
	return module, nil
}

func InitHandler(db *gorm.DB) *web.Handler {
	service := InitService(db)
	handler := web.NewHandler(service)
	return handler
}

func InitService(db *gorm.DB) service.Service {
	productDAO := InitTablesOnce(db)
	productRepository := repository.NewProductRepository(productDAO)
	serviceService := service.NewService(productRepository)
	return serviceService
}

// wire.go:

type (
	Handler = web.Handler
	Service = service.Service
	SKU     = domain.SKU
	SPU     = domain.SPU
	Status  = domain.Status
)

const (
	StatusOffShelf    = domain.StatusOffShelf
	StatusOnShelf     = domain.StatusOnShelf
	SaleTypeUnlimited = domain.SaleTypeUnlimited
)

var ServiceSet = wire.NewSet(
	InitTablesOnce, repository.NewProductRepository, service.NewService,
)

var HandlerSet = wire.NewSet(
	InitService, web.NewHandler,
)

func InitConsumer(svc service.Service, cmq mq.MQ) *event.ProductConsumer {
	consumer, err := event.NewProductConsumer(svc, cmq)
	if err != nil {
		panic(err)
	}
	consumer.Start(context.Background())
	return consumer
}

var once = &sync.Once{}

func InitTablesOnce(db *egorm.Component) dao.ProductDAO {
	once.Do(func() {
		_ = dao.InitTables(db)
	})
	return dao.NewProductGORMDAO(db)
}
