// Code generated by MockGen. DO NOT EDIT.
// Source: ./admin.go
//
// Generated by this command:
//
//	mockgen -source=./admin.go -destination=../../mocks/admin.mock.go -package=roadmapmocks -typed=true AdminService
//

// Package roadmapmocks is a generated GoMock package.
package roadmapmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ecodeclub/webook/internal/roadmap/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminService is a mock of AdminService interface.
type MockAdminService struct {
	ctrl     *gomock.Controller
	recorder *MockAdminServiceMockRecorder
	isgomock struct{}
}

// MockAdminServiceMockRecorder is the mock recorder for MockAdminService.
type MockAdminServiceMockRecorder struct {
	mock *MockAdminService
}

// NewMockAdminService creates a new mock instance.
func NewMockAdminService(ctrl *gomock.Controller) *MockAdminService {
	mock := &MockAdminService{ctrl: ctrl}
	mock.recorder = &MockAdminServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminService) EXPECT() *MockAdminServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAdminService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdminServiceMockRecorder) Delete(ctx, id any) *MockAdminServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdminService)(nil).Delete), ctx, id)
	return &MockAdminServiceDeleteCall{Call: call}
}

// MockAdminServiceDeleteCall wrap *gomock.Call
type MockAdminServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminServiceDeleteCall) Return(arg0 error) *MockAdminServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminServiceDeleteCall) Do(f func(context.Context, int64) error) *MockAdminServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminServiceDeleteCall) DoAndReturn(f func(context.Context, int64) error) *MockAdminServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteEdge mocks base method.
func (m *MockAdminService) DeleteEdge(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEdge", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEdge indicates an expected call of DeleteEdge.
func (mr *MockAdminServiceMockRecorder) DeleteEdge(ctx, id any) *MockAdminServiceDeleteEdgeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEdge", reflect.TypeOf((*MockAdminService)(nil).DeleteEdge), ctx, id)
	return &MockAdminServiceDeleteEdgeCall{Call: call}
}

// MockAdminServiceDeleteEdgeCall wrap *gomock.Call
type MockAdminServiceDeleteEdgeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminServiceDeleteEdgeCall) Return(arg0 error) *MockAdminServiceDeleteEdgeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminServiceDeleteEdgeCall) Do(f func(context.Context, int64) error) *MockAdminServiceDeleteEdgeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminServiceDeleteEdgeCall) DoAndReturn(f func(context.Context, int64) error) *MockAdminServiceDeleteEdgeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteNode mocks base method.
func (m *MockAdminService) DeleteNode(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNode", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNode indicates an expected call of DeleteNode.
func (mr *MockAdminServiceMockRecorder) DeleteNode(ctx, id any) *MockAdminServiceDeleteNodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNode", reflect.TypeOf((*MockAdminService)(nil).DeleteNode), ctx, id)
	return &MockAdminServiceDeleteNodeCall{Call: call}
}

// MockAdminServiceDeleteNodeCall wrap *gomock.Call
type MockAdminServiceDeleteNodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminServiceDeleteNodeCall) Return(arg0 error) *MockAdminServiceDeleteNodeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminServiceDeleteNodeCall) Do(f func(context.Context, int64) error) *MockAdminServiceDeleteNodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminServiceDeleteNodeCall) DoAndReturn(f func(context.Context, int64) error) *MockAdminServiceDeleteNodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Detail mocks base method.
func (m *MockAdminService) Detail(ctx context.Context, id int64) (domain.Roadmap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, id)
	ret0, _ := ret[0].(domain.Roadmap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockAdminServiceMockRecorder) Detail(ctx, id any) *MockAdminServiceDetailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockAdminService)(nil).Detail), ctx, id)
	return &MockAdminServiceDetailCall{Call: call}
}

// MockAdminServiceDetailCall wrap *gomock.Call
type MockAdminServiceDetailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminServiceDetailCall) Return(arg0 domain.Roadmap, arg1 error) *MockAdminServiceDetailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminServiceDetailCall) Do(f func(context.Context, int64) (domain.Roadmap, error)) *MockAdminServiceDetailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminServiceDetailCall) DoAndReturn(f func(context.Context, int64) (domain.Roadmap, error)) *MockAdminServiceDetailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockAdminService) List(ctx context.Context, offset, limit int) ([]domain.Roadmap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Roadmap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAdminServiceMockRecorder) List(ctx, offset, limit any) *MockAdminServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAdminService)(nil).List), ctx, offset, limit)
	return &MockAdminServiceListCall{Call: call}
}

// MockAdminServiceListCall wrap *gomock.Call
type MockAdminServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminServiceListCall) Return(arg0 []domain.Roadmap, arg1 error) *MockAdminServiceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminServiceListCall) Do(f func(context.Context, int, int) ([]domain.Roadmap, error)) *MockAdminServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminServiceListCall) DoAndReturn(f func(context.Context, int, int) ([]domain.Roadmap, error)) *MockAdminServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSince mocks base method.
func (m *MockAdminService) ListSince(ctx context.Context, since int64, offset, limit int) ([]domain.Roadmap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSince", ctx, since, offset, limit)
	ret0, _ := ret[0].([]domain.Roadmap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSince indicates an expected call of ListSince.
func (mr *MockAdminServiceMockRecorder) ListSince(ctx, since, offset, limit any) *MockAdminServiceListSinceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSince", reflect.TypeOf((*MockAdminService)(nil).ListSince), ctx, since, offset, limit)
	return &MockAdminServiceListSinceCall{Call: call}
}

// MockAdminServiceListSinceCall wrap *gomock.Call
type MockAdminServiceListSinceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminServiceListSinceCall) Return(arg0 []domain.Roadmap, arg1 error) *MockAdminServiceListSinceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminServiceListSinceCall) Do(f func(context.Context, int64, int, int) ([]domain.Roadmap, error)) *MockAdminServiceListSinceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminServiceListSinceCall) DoAndReturn(f func(context.Context, int64, int, int) ([]domain.Roadmap, error)) *MockAdminServiceListSinceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NodeList mocks base method.
func (m *MockAdminService) NodeList(ctx context.Context, rid int64) ([]domain.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeList", ctx, rid)
	ret0, _ := ret[0].([]domain.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeList indicates an expected call of NodeList.
func (mr *MockAdminServiceMockRecorder) NodeList(ctx, rid any) *MockAdminServiceNodeListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeList", reflect.TypeOf((*MockAdminService)(nil).NodeList), ctx, rid)
	return &MockAdminServiceNodeListCall{Call: call}
}

// MockAdminServiceNodeListCall wrap *gomock.Call
type MockAdminServiceNodeListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminServiceNodeListCall) Return(arg0 []domain.Node, arg1 error) *MockAdminServiceNodeListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminServiceNodeListCall) Do(f func(context.Context, int64) ([]domain.Node, error)) *MockAdminServiceNodeListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminServiceNodeListCall) DoAndReturn(f func(context.Context, int64) ([]domain.Node, error)) *MockAdminServiceNodeListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SanitizeData mocks base method.
func (m *MockAdminService) SanitizeData() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SanitizeData")
}

// SanitizeData indicates an expected call of SanitizeData.
func (mr *MockAdminServiceMockRecorder) SanitizeData() *MockAdminServiceSanitizeDataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeData", reflect.TypeOf((*MockAdminService)(nil).SanitizeData))
	return &MockAdminServiceSanitizeDataCall{Call: call}
}

// MockAdminServiceSanitizeDataCall wrap *gomock.Call
type MockAdminServiceSanitizeDataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminServiceSanitizeDataCall) Return() *MockAdminServiceSanitizeDataCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminServiceSanitizeDataCall) Do(f func()) *MockAdminServiceSanitizeDataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminServiceSanitizeDataCall) DoAndReturn(f func()) *MockAdminServiceSanitizeDataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockAdminService) Save(ctx context.Context, r domain.Roadmap) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, r)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockAdminServiceMockRecorder) Save(ctx, r any) *MockAdminServiceSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAdminService)(nil).Save), ctx, r)
	return &MockAdminServiceSaveCall{Call: call}
}

// MockAdminServiceSaveCall wrap *gomock.Call
type MockAdminServiceSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminServiceSaveCall) Return(arg0 int64, arg1 error) *MockAdminServiceSaveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminServiceSaveCall) Do(f func(context.Context, domain.Roadmap) (int64, error)) *MockAdminServiceSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminServiceSaveCall) DoAndReturn(f func(context.Context, domain.Roadmap) (int64, error)) *MockAdminServiceSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveEdge mocks base method.
func (m *MockAdminService) SaveEdge(ctx context.Context, rid int64, edge domain.Edge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEdge", ctx, rid, edge)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEdge indicates an expected call of SaveEdge.
func (mr *MockAdminServiceMockRecorder) SaveEdge(ctx, rid, edge any) *MockAdminServiceSaveEdgeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEdge", reflect.TypeOf((*MockAdminService)(nil).SaveEdge), ctx, rid, edge)
	return &MockAdminServiceSaveEdgeCall{Call: call}
}

// MockAdminServiceSaveEdgeCall wrap *gomock.Call
type MockAdminServiceSaveEdgeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminServiceSaveEdgeCall) Return(arg0 error) *MockAdminServiceSaveEdgeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminServiceSaveEdgeCall) Do(f func(context.Context, int64, domain.Edge) error) *MockAdminServiceSaveEdgeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminServiceSaveEdgeCall) DoAndReturn(f func(context.Context, int64, domain.Edge) error) *MockAdminServiceSaveEdgeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveNode mocks base method.
func (m *MockAdminService) SaveNode(ctx context.Context, node domain.Node) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNode", ctx, node)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveNode indicates an expected call of SaveNode.
func (mr *MockAdminServiceMockRecorder) SaveNode(ctx, node any) *MockAdminServiceSaveNodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNode", reflect.TypeOf((*MockAdminService)(nil).SaveNode), ctx, node)
	return &MockAdminServiceSaveNodeCall{Call: call}
}

// MockAdminServiceSaveNodeCall wrap *gomock.Call
type MockAdminServiceSaveNodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminServiceSaveNodeCall) Return(arg0 int64, arg1 error) *MockAdminServiceSaveNodeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminServiceSaveNodeCall) Do(f func(context.Context, domain.Node) (int64, error)) *MockAdminServiceSaveNodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminServiceSaveNodeCall) DoAndReturn(f func(context.Context, domain.Node) (int64, error)) *MockAdminServiceSaveNodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
