// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/ecodeclub/webook/internal/credit"
	"github.com/ecodeclub/webook/internal/order"
	"github.com/ecodeclub/webook/internal/order/internal/web"
	"github.com/ecodeclub/webook/internal/payment"
	"github.com/ecodeclub/webook/internal/product"
	testioc "github.com/ecodeclub/webook/internal/test/ioc"
)

// Injectors from wire.go:

func InitHandler(pm *payment.Module, ppm *product.Module, cm *credit.Module) (*web.Handler, error) {
	cache := testioc.InitCache()
	db := testioc.InitDB()
	service := order.InitService(db)
	handler := order.InitHandler(cache, service, pm, ppm, cm)
	return handler, nil
}
