// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package marketing

import (
	"github.com/ecodeclub/mq-api"
	"github.com/ecodeclub/webook/internal/marketing/internal/event/producer"
	"github.com/ecodeclub/webook/internal/marketing/internal/repository"
	"github.com/ecodeclub/webook/internal/marketing/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/marketing/internal/service"
	"github.com/ecodeclub/webook/internal/marketing/internal/web"
	"github.com/ecodeclub/webook/internal/order"
	"github.com/ecodeclub/webook/internal/pkg/sequencenumber"
	"github.com/lithammer/shortuuid/v4"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB, q mq.MQ, om *order.Module) (*Module, error) {
	marketingDAO := dao.NewGORMMarketingDAO(db)
	marketingRepository := repository.NewRepository(marketingDAO)
	serviceService := om.Svc
	generator := sequencenumber.NewGenerator()
	v := redemptionCodeGenerator(generator)
	v2 := eventKeyGenerator()
	memberEventProducer, err := producer.NewMemberEventProducer(q)
	if err != nil {
		return nil, err
	}
	creditEventProducer, err := producer.NewCreditEventProducer(q)
	if err != nil {
		return nil, err
	}
	permissionEventProducer, err := producer.NewPermissionEventProducer(q)
	if err != nil {
		return nil, err
	}
	service2 := service.NewService(marketingRepository, serviceService, v, v2, memberEventProducer, creditEventProducer, permissionEventProducer)
	handler := web.NewHandler(service2)
	module := &Module{
		Svc: service2,
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

type (
	Service = service.Service
	Handler = web.Handler
)

func redemptionCodeGenerator(generator *sequencenumber.Generator) func(id int64) string {
	return func(id int64) string {
		code, _ := generator.Generate(id)
		return code
	}
}

func eventKeyGenerator() func() string {
	return shortuuid.New
}
