// Code generated by MockGen. DO NOT EDIT.
// Source: ./question_set.go
//
// Generated by this command:
//
//	mockgen -source=./question_set.go -destination=../../mocks/quetion_set.mock.go -package=quemocks -typed=true QuestionSetService
//

// Package quemocks is a generated GoMock package.
package quemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ecodeclub/webook/internal/question/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQuestionSetService is a mock of QuestionSetService interface.
type MockQuestionSetService struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionSetServiceMockRecorder
}

// MockQuestionSetServiceMockRecorder is the mock recorder for MockQuestionSetService.
type MockQuestionSetServiceMockRecorder struct {
	mock *MockQuestionSetService
}

// NewMockQuestionSetService creates a new mock instance.
func NewMockQuestionSetService(ctrl *gomock.Controller) *MockQuestionSetService {
	mock := &MockQuestionSetService{ctrl: ctrl}
	mock.recorder = &MockQuestionSetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionSetService) EXPECT() *MockQuestionSetServiceMockRecorder {
	return m.recorder
}

// Detail mocks base method.
func (m *MockQuestionSetService) Detail(ctx context.Context, id int64) (domain.QuestionSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, id)
	ret0, _ := ret[0].(domain.QuestionSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockQuestionSetServiceMockRecorder) Detail(ctx, id any) *MockQuestionSetServiceDetailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockQuestionSetService)(nil).Detail), ctx, id)
	return &MockQuestionSetServiceDetailCall{Call: call}
}

// MockQuestionSetServiceDetailCall wrap *gomock.Call
type MockQuestionSetServiceDetailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionSetServiceDetailCall) Return(arg0 domain.QuestionSet, arg1 error) *MockQuestionSetServiceDetailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionSetServiceDetailCall) Do(f func(context.Context, int64) (domain.QuestionSet, error)) *MockQuestionSetServiceDetailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionSetServiceDetailCall) DoAndReturn(f func(context.Context, int64) (domain.QuestionSet, error)) *MockQuestionSetServiceDetailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DetailByBiz mocks base method.
func (m *MockQuestionSetService) DetailByBiz(ctx context.Context, biz string, bizId int64) (domain.QuestionSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailByBiz", ctx, biz, bizId)
	ret0, _ := ret[0].(domain.QuestionSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailByBiz indicates an expected call of DetailByBiz.
func (mr *MockQuestionSetServiceMockRecorder) DetailByBiz(ctx, biz, bizId any) *MockQuestionSetServiceDetailByBizCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailByBiz", reflect.TypeOf((*MockQuestionSetService)(nil).DetailByBiz), ctx, biz, bizId)
	return &MockQuestionSetServiceDetailByBizCall{Call: call}
}

// MockQuestionSetServiceDetailByBizCall wrap *gomock.Call
type MockQuestionSetServiceDetailByBizCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionSetServiceDetailByBizCall) Return(arg0 domain.QuestionSet, arg1 error) *MockQuestionSetServiceDetailByBizCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionSetServiceDetailByBizCall) Do(f func(context.Context, string, int64) (domain.QuestionSet, error)) *MockQuestionSetServiceDetailByBizCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionSetServiceDetailByBizCall) DoAndReturn(f func(context.Context, string, int64) (domain.QuestionSet, error)) *MockQuestionSetServiceDetailByBizCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByIDsWithQuestion mocks base method.
func (m *MockQuestionSetService) GetByIDsWithQuestion(ctx context.Context, ids []int64) ([]domain.QuestionSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDsWithQuestion", ctx, ids)
	ret0, _ := ret[0].([]domain.QuestionSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDsWithQuestion indicates an expected call of GetByIDsWithQuestion.
func (mr *MockQuestionSetServiceMockRecorder) GetByIDsWithQuestion(ctx, ids any) *MockQuestionSetServiceGetByIDsWithQuestionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDsWithQuestion", reflect.TypeOf((*MockQuestionSetService)(nil).GetByIDsWithQuestion), ctx, ids)
	return &MockQuestionSetServiceGetByIDsWithQuestionCall{Call: call}
}

// MockQuestionSetServiceGetByIDsWithQuestionCall wrap *gomock.Call
type MockQuestionSetServiceGetByIDsWithQuestionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionSetServiceGetByIDsWithQuestionCall) Return(arg0 []domain.QuestionSet, arg1 error) *MockQuestionSetServiceGetByIDsWithQuestionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionSetServiceGetByIDsWithQuestionCall) Do(f func(context.Context, []int64) ([]domain.QuestionSet, error)) *MockQuestionSetServiceGetByIDsWithQuestionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionSetServiceGetByIDsWithQuestionCall) DoAndReturn(f func(context.Context, []int64) ([]domain.QuestionSet, error)) *MockQuestionSetServiceGetByIDsWithQuestionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByIds mocks base method.
func (m *MockQuestionSetService) GetByIds(ctx context.Context, ids []int64) ([]domain.QuestionSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.QuestionSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockQuestionSetServiceMockRecorder) GetByIds(ctx, ids any) *MockQuestionSetServiceGetByIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockQuestionSetService)(nil).GetByIds), ctx, ids)
	return &MockQuestionSetServiceGetByIdsCall{Call: call}
}

// MockQuestionSetServiceGetByIdsCall wrap *gomock.Call
type MockQuestionSetServiceGetByIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionSetServiceGetByIdsCall) Return(arg0 []domain.QuestionSet, arg1 error) *MockQuestionSetServiceGetByIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionSetServiceGetByIdsCall) Do(f func(context.Context, []int64) ([]domain.QuestionSet, error)) *MockQuestionSetServiceGetByIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionSetServiceGetByIdsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.QuestionSet, error)) *MockQuestionSetServiceGetByIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCandidates mocks base method.
func (m *MockQuestionSetService) GetCandidates(ctx context.Context, id int64, offset, limit int) ([]domain.Question, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCandidates", ctx, id, offset, limit)
	ret0, _ := ret[0].([]domain.Question)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCandidates indicates an expected call of GetCandidates.
func (mr *MockQuestionSetServiceMockRecorder) GetCandidates(ctx, id, offset, limit any) *MockQuestionSetServiceGetCandidatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCandidates", reflect.TypeOf((*MockQuestionSetService)(nil).GetCandidates), ctx, id, offset, limit)
	return &MockQuestionSetServiceGetCandidatesCall{Call: call}
}

// MockQuestionSetServiceGetCandidatesCall wrap *gomock.Call
type MockQuestionSetServiceGetCandidatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionSetServiceGetCandidatesCall) Return(arg0 []domain.Question, arg1 int64, arg2 error) *MockQuestionSetServiceGetCandidatesCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionSetServiceGetCandidatesCall) Do(f func(context.Context, int64, int, int) ([]domain.Question, int64, error)) *MockQuestionSetServiceGetCandidatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionSetServiceGetCandidatesCall) DoAndReturn(f func(context.Context, int64, int, int) ([]domain.Question, int64, error)) *MockQuestionSetServiceGetCandidatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockQuestionSetService) List(ctx context.Context, offset, limit int) ([]domain.QuestionSet, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.QuestionSet)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockQuestionSetServiceMockRecorder) List(ctx, offset, limit any) *MockQuestionSetServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockQuestionSetService)(nil).List), ctx, offset, limit)
	return &MockQuestionSetServiceListCall{Call: call}
}

// MockQuestionSetServiceListCall wrap *gomock.Call
type MockQuestionSetServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionSetServiceListCall) Return(arg0 []domain.QuestionSet, arg1 int64, arg2 error) *MockQuestionSetServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionSetServiceListCall) Do(f func(context.Context, int, int) ([]domain.QuestionSet, int64, error)) *MockQuestionSetServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionSetServiceListCall) DoAndReturn(f func(context.Context, int, int) ([]domain.QuestionSet, int64, error)) *MockQuestionSetServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDefault mocks base method.
func (m *MockQuestionSetService) ListDefault(ctx context.Context, offset, limit int) ([]domain.QuestionSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDefault", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.QuestionSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDefault indicates an expected call of ListDefault.
func (mr *MockQuestionSetServiceMockRecorder) ListDefault(ctx, offset, limit any) *MockQuestionSetServiceListDefaultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDefault", reflect.TypeOf((*MockQuestionSetService)(nil).ListDefault), ctx, offset, limit)
	return &MockQuestionSetServiceListDefaultCall{Call: call}
}

// MockQuestionSetServiceListDefaultCall wrap *gomock.Call
type MockQuestionSetServiceListDefaultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionSetServiceListDefaultCall) Return(arg0 []domain.QuestionSet, arg1 error) *MockQuestionSetServiceListDefaultCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionSetServiceListDefaultCall) Do(f func(context.Context, int, int) ([]domain.QuestionSet, error)) *MockQuestionSetServiceListDefaultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionSetServiceListDefaultCall) DoAndReturn(f func(context.Context, int, int) ([]domain.QuestionSet, error)) *MockQuestionSetServiceListDefaultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockQuestionSetService) Save(ctx context.Context, set domain.QuestionSet) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, set)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockQuestionSetServiceMockRecorder) Save(ctx, set any) *MockQuestionSetServiceSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockQuestionSetService)(nil).Save), ctx, set)
	return &MockQuestionSetServiceSaveCall{Call: call}
}

// MockQuestionSetServiceSaveCall wrap *gomock.Call
type MockQuestionSetServiceSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionSetServiceSaveCall) Return(arg0 int64, arg1 error) *MockQuestionSetServiceSaveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionSetServiceSaveCall) Do(f func(context.Context, domain.QuestionSet) (int64, error)) *MockQuestionSetServiceSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionSetServiceSaveCall) DoAndReturn(f func(context.Context, domain.QuestionSet) (int64, error)) *MockQuestionSetServiceSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateQuestions mocks base method.
func (m *MockQuestionSetService) UpdateQuestions(ctx context.Context, set domain.QuestionSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestions", ctx, set)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQuestions indicates an expected call of UpdateQuestions.
func (mr *MockQuestionSetServiceMockRecorder) UpdateQuestions(ctx, set any) *MockQuestionSetServiceUpdateQuestionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestions", reflect.TypeOf((*MockQuestionSetService)(nil).UpdateQuestions), ctx, set)
	return &MockQuestionSetServiceUpdateQuestionsCall{Call: call}
}

// MockQuestionSetServiceUpdateQuestionsCall wrap *gomock.Call
type MockQuestionSetServiceUpdateQuestionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionSetServiceUpdateQuestionsCall) Return(arg0 error) *MockQuestionSetServiceUpdateQuestionsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionSetServiceUpdateQuestionsCall) Do(f func(context.Context, domain.QuestionSet) error) *MockQuestionSetServiceUpdateQuestionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionSetServiceUpdateQuestionsCall) DoAndReturn(f func(context.Context, domain.QuestionSet) error) *MockQuestionSetServiceUpdateQuestionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
