// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package label

import (
	"sync"

	"github.com/ecodeclub/webook/internal/label/internal/repository"
	"github.com/ecodeclub/webook/internal/label/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/label/internal/service"
	"github.com/ecodeclub/webook/internal/label/internal/web"
	"github.com/ego-component/egorm"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitHandler(db *gorm.DB) *web.Handler {
	labelDAO := InitTablesOnce(db)
	labelRepository := repository.NewCachedLabelRepository(labelDAO)
	serviceService := service.NewService(labelRepository)
	handler := web.NewHandler(serviceService)
	return handler
}

// wire.go:

var HandlerSet = wire.NewSet(repository.NewCachedLabelRepository, InitTablesOnce, service.NewService, web.NewHandler)

var once = &sync.Once{}

func InitTablesOnce(db *egorm.Component) dao.LabelDAO {
	once.Do(func() {
		dao.InitTables(db)
	})
	return dao.NewLabelGORMDAO(db)
}

type Handler = web.Handler
