// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"fmt"

	"github.com/ecodeclub/webook/internal/kbase"
	"github.com/ecodeclub/webook/internal/kbase/internal/domain"
	"github.com/ecodeclub/webook/internal/kbase/internal/service"
	"github.com/ecodeclub/webook/internal/kbase/internal/service/syncer"
	"github.com/ecodeclub/webook/internal/kbase/internal/web"
	baguwen "github.com/ecodeclub/webook/internal/question"
	"github.com/ecodeclub/webook/internal/roadmap"
)

// Injectors from wire.go:

func InitModule(queModule *baguwen.Module, rdModule *roadmap.Module, svc service.Service) *kbase.Module {
	serviceService := queModule.Svc
	adminService := rdModule.AdminSvc
	v := initSyncerMap(serviceService, adminService, svc)
	syncService := service.NewSyncService(v)
	adminHandler := web.NewAdminHandler(syncService)
	module := &kbase.Module{
		AdminHdl: adminHandler,
	}
	return module
}

// wire.go:

func initSyncerMap(baguwenSvc baguwen.Service, rdSvc roadmap.AdminService, svc service.Service) map[string]service.Syncer {
	questionIndexName := fmt.Sprintf("%s_index", domain.BizQuestion)
	questionRelIndexName := fmt.Sprintf("%s_index", domain.BizQuestionRel)
	batchSize := 100
	return map[string]service.Syncer{domain.BizQuestion: syncer.NewQuestionSyncer(questionIndexName,
		batchSize, baguwenSvc, svc), domain.BizQuestionRel: syncer.NewQuestionRelSyncer(questionRelIndexName,
		batchSize, rdSvc, svc),
	}
}
