// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ai

import (
	"sync"

	"github.com/ecodeclub/webook/internal/ai/internal/repository"
	"github.com/ecodeclub/webook/internal/ai/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/ai/internal/service/gpt"
	"github.com/ecodeclub/webook/internal/ai/internal/service/gpt/handler/config"
	credit2 "github.com/ecodeclub/webook/internal/ai/internal/service/gpt/handler/credit"
	"github.com/ecodeclub/webook/internal/ai/internal/service/gpt/handler/log"
	"github.com/ecodeclub/webook/internal/ai/internal/service/gpt/handler/record"
	"github.com/ecodeclub/webook/internal/credit"
	"github.com/ego-component/egorm"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB, creditSvc *credit.Module) (*Module, error) {
	handlerBuilder := log.NewHandler()
	configDAO := dao.NewGORMConfigDAO(db)
	configRepository := repository.NewCachedConfigRepository(configDAO)
	configHandlerBuilder := config.NewBuilder(configRepository)
	service := creditSvc.Svc
	gptCreditDAO := InitGPTCreditLogDAO(db)
	gptCreditLogRepo := repository.NewGPTCreditLogRepo(gptCreditDAO)
	creditHandlerBuilder := credit2.NewHandlerBuilder(service, gptCreditLogRepo)
	gptRecordDAO := dao.NewGORMGPTLogDAO(db)
	gptLogRepo := repository.NewGPTLogRepo(gptRecordDAO)
	recordHandlerBuilder := record.NewHandler(gptLogRepo)
	v := InitCommonHandlers(handlerBuilder, configHandlerBuilder, creditHandlerBuilder, recordHandlerBuilder)
	handler := InitZhipu()
	facadeHandler := InitHandlerFacade(v, handler)
	gptService := gpt.NewGPTService(facadeHandler)
	module := &Module{
		Svc: gptService,
	}
	return module, nil
}

// wire.go:

var daoOnce = sync.Once{}

func InitTableOnce(db *gorm.DB) {
	daoOnce.Do(func() {
		err := dao.InitTables(db)
		if err != nil {
			panic(err)
		}
	})
}

func InitGPTCreditLogDAO(db *egorm.Component) dao.GPTCreditDAO {
	InitTableOnce(db)
	return dao.NewGPTCreditLogDAO(db)
}
