// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package credit

import (
	"context"
	"sync"

	"github.com/ecodeclub/mq-api"
	"github.com/ecodeclub/webook/internal/credit/internal/domain"
	"github.com/ecodeclub/webook/internal/credit/internal/event"
	"github.com/ecodeclub/webook/internal/credit/internal/repository"
	"github.com/ecodeclub/webook/internal/credit/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/credit/internal/service"
	svcmocks "github.com/ecodeclub/webook/internal/credit/internal/service/mocks"
	"github.com/ego-component/egorm"
	"go.uber.org/mock/gomock"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB, q mq.MQ) (*Module, error) {
	service := InitService(db)
	creditConsumer := initCreditConsumer(service, q)
	module := &Module{
		Svc: service,
		c:   creditConsumer,
	}
	return module, nil
}

// wire.go:

type Credit = domain.Credit

type Service = service.Service

type MockCreditService = svcmocks.MockService

// todo: 在credit下建立mocks, 然后去掉这里
func NewMockCreditService(ctrl *gomock.Controller) *MockCreditService {
	return svcmocks.NewMockService(ctrl)
}

var (
	once = &sync.Once{}
	svc  service.Service
)

func InitService(db *egorm.Component) Service {
	once.Do(func() {
		_ = dao.InitTables(db)
		d := dao.NewCreditGORMDAO(db)
		r := repository.NewCreditRepository(d)
		svc = service.NewCreditService(r)
	})
	return svc
}

func initCreditConsumer(svc2 service.Service, q mq.MQ) *event.CreditConsumer {
	c, err := event.NewCreditConsumer(svc2, q)
	if err != nil {
		panic(err)
	}
	c.Start(context.Background())
	return c
}
