// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"sync"

	"github.com/ecodeclub/webook/internal/credit"
	"github.com/ecodeclub/webook/internal/payment"
	"github.com/ecodeclub/webook/internal/payment/internal/event"
	"github.com/ecodeclub/webook/internal/payment/internal/repository"
	"github.com/ecodeclub/webook/internal/payment/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/payment/internal/service"
	"github.com/ecodeclub/webook/internal/payment/internal/service/wechat"
	"github.com/ecodeclub/webook/internal/payment/internal/web"
	"github.com/ecodeclub/webook/internal/payment/ioc"
	"github.com/ecodeclub/webook/internal/pkg/sequencenumber"
	testioc "github.com/ecodeclub/webook/internal/test/ioc"
	"github.com/gotomicro/ego/core/elog"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitModule(p event.PaymentEventProducer, paymentDDLFunc func() int64, cm *credit.Module, h wechat.NotifyHandler, native wechat.NativeAPIService) *payment.Module {
	db := testioc.InitDB()
	daoPaymentDAO := InitDAO(db)
	paymentRepository := repository.NewPaymentRepository(daoPaymentDAO)
	component := initLogger()
	wechatConfig := initWechatConfig()
	nativePaymentService := ioc.InitWechatNativeService(native, paymentRepository, p, paymentDDLFunc, component, wechatConfig)
	handler := web.NewHandler(h, nativePaymentService)
	serviceService := cm.Svc
	generator := sequencenumber.NewGenerator()
	service2 := service.NewService(nativePaymentService, serviceService, generator, paymentRepository)
	module := &payment.Module{
		Hdl: handler,
		Svc: service2,
	}
	return module
}

// wire.go:

var (
	once       = &sync.Once{}
	paymentDAO dao.PaymentDAO
)

func InitDAO(db *gorm.DB) dao.PaymentDAO {
	once.Do(func() {
		_ = dao.InitTables(db)
		paymentDAO = dao.NewPaymentGORMDAO(db)
	})
	return paymentDAO
}

func initLogger() *elog.Component {
	return elog.DefaultLogger
}

func initWechatConfig() ioc.WechatConfig {
	return ioc.WechatConfig{
		AppID: "MockAPPID",
		MchID: "MockMchID",
	}
}
