// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package interview

import (
	"sync"

	"github.com/ecodeclub/webook/internal/interview/internal/repository"
	"github.com/ecodeclub/webook/internal/interview/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/interview/internal/service"
	"github.com/ecodeclub/webook/internal/interview/internal/web"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB) (*Module, error) {
	interviewDAO := initDAO(db)
	interviewRepository := repository.NewInterviewRepository(interviewDAO)
	interviewService := service.NewInterviewService(interviewRepository)
	interviewJourneyHandler := web.NewInterviewJourneyHandler(interviewService)
	module := &Module{
		JourneyHdl: interviewJourneyHandler,
	}
	return module, nil
}

// wire.go:

type (
	JourneyHandler = web.InterviewJourneyHandler
)

var initOnce sync.Once

func initDAO(db *gorm.DB) dao.InterviewDAO {
	initOnce.Do(func() {
		err := dao.InitTables(db)
		if err != nil {
			panic(err)
		}
	})
	return dao.NewGORMInterviewDAO(db)
}
