// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package member

import (
	"github.com/ecodeclub/webook/internal/member/internal/domain"
	"github.com/ecodeclub/webook/internal/member/internal/repository"
	"github.com/ecodeclub/webook/internal/member/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/member/internal/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitService(db *gorm.DB) service.Service {
	memberDAO := dao.NewMemberGORMDAO(db)
	memberRepository := repository.NewMemberRepository(memberDAO)
	serviceService := service.NewMemberService(memberRepository)
	return serviceService
}

// wire.go:

type Member = domain.Member

type Service = service.Service

var serviceSet = wire.NewSet(dao.NewMemberGORMDAO, repository.NewMemberRepository, service.NewMemberService)
