// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/ecodeclub/ecache"
	"github.com/ecodeclub/ginx/session"
	"github.com/ecodeclub/mq-api"
	"github.com/ecodeclub/webook/internal/member"
	"github.com/ecodeclub/webook/internal/permission"
	"github.com/ecodeclub/webook/internal/sms/client"
	"github.com/ecodeclub/webook/internal/user/internal/repository"
	"github.com/ecodeclub/webook/internal/user/internal/repository/cache"
	"github.com/ecodeclub/webook/internal/user/internal/service"
	"github.com/ego-component/egorm"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(db *egorm.Component, cache2 ecache.Cache, q mq.MQ, creators []string, memberSvc *member.Module, sp session.Provider, permissionSvc *permission.Module, smsClient client.Client) *Module {
	userWechatWebOAuth2Service := initWechatWebOAuthService(cache2)
	userWechatMiniOAuth2Service := initWechatMiniOAuthService()
	userDAO := initDAO(db)
	userCache := cache.NewUserECache(cache2)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache)
	registrationEventProducer := initRegistrationEventProducer(q)
	userService := service.NewUserService(userRepository, registrationEventProducer)
	v := memberSvc.Svc
	verificationCodeCache := cache.NewVerificationCodeCache(cache2)
	verificationCodeRepo := repository.NewVerificationCodeRepository(verificationCodeCache)
	verificationCodeSvc := initVerificationCodeSvc(smsClient, verificationCodeRepo)
	v2 := permissionSvc.Svc
	v3 := iniHandler(userWechatWebOAuth2Service, userWechatMiniOAuth2Service, userService, v, sp, verificationCodeSvc, v2, creators)
	module := &Module{
		Hdl: v3,
		Svc: userService,
	}
	return module
}

// wire.go:

var ProviderSet = wire.NewSet(
	iniHandler, cache.NewUserECache, initDAO,
	initWechatWebOAuthService,
	initWechatMiniOAuthService,
	initRegistrationEventProducer, service.NewUserService, repository.NewCachedUserRepository,
)

var verificationCodeRepoSet = wire.NewSet(cache.NewVerificationCodeCache, repository.NewVerificationCodeRepository)
