// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/ecodeclub/ecache"
	"github.com/ecodeclub/mq-api"
	"github.com/ecodeclub/webook/internal/member"
	"github.com/ecodeclub/webook/internal/user/internal/event"
	"github.com/ecodeclub/webook/internal/user/internal/repository"
	"github.com/ecodeclub/webook/internal/user/internal/repository/cache"
	"github.com/ecodeclub/webook/internal/user/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/user/internal/service"
	"github.com/ecodeclub/webook/internal/user/internal/web"
	"github.com/ego-component/egorm"
	"github.com/google/wire"
	"github.com/gotomicro/ego/core/econf"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitHandler(db *gorm.DB, cache2 ecache.Cache, q mq.MQ, creators []string, memberSvc *member.Module) *web.Handler {
	oAuth2Service := initWechatService()
	userDAO := initDAO(db)
	userCache := cache.NewUserECache(cache2)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache)
	registrationEventProducer := initRegistrationEventProducer(q)
	userService := service.NewUserService(userRepository, registrationEventProducer)
	serviceService := memberSvc.Svc
	handler := web.NewHandler(oAuth2Service, userService, serviceService, creators)
	return handler
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, cache.NewUserECache, initDAO,
	initWechatService,
	initRegistrationEventProducer, service.NewUserService, repository.NewCachedUserRepository,
)

func initWechatService() service.OAuth2Service {
	type Config struct {
		AppSecretID      string `yaml:"appSecretID"`
		AppSecretKey     string `yaml:"appSecretKey"`
		LoginRedirectURL string `yaml:"loginRedirectURL"`
	}
	var cfg Config
	err := econf.UnmarshalKey("wechat", &cfg)
	if err != nil {
		panic(err)
	}
	return service.NewWechatService(cfg.AppSecretID, cfg.AppSecretKey, cfg.LoginRedirectURL)
}

func initDAO(db *egorm.Component) dao.UserDAO {
	err := dao.InitTables(db)
	if err != nil {
		panic(err)
	}
	return dao.NewGORMUserDAO(db)
}

func initRegistrationEventProducer(q mq.MQ) event.RegistrationEventProducer {
	producer, err := event.NewRegistrationEventProducer(q)
	if err != nil {
		panic(err)
	}
	return producer
}

// Handler 暴露出去给 ioc 使用
type Handler = web.Handler
