// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/ecodeclub/webook/internal/cases"
	baguwen "github.com/ecodeclub/webook/internal/question"
	"github.com/ecodeclub/webook/internal/skill"
	"github.com/ecodeclub/webook/internal/skill/internal/web"
	testioc "github.com/ecodeclub/webook/internal/test/ioc"
)

// Injectors from wire.go:

func InitHandler(bm *baguwen.Module, cm *cases.Module) (*web.Handler, error) {
	db := testioc.InitDB()
	cache := testioc.InitCache()
	handler, err := skill.InitHandler(db, cache, bm, cm)
	if err != nil {
		return nil, err
	}
	return handler, nil
}
