// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package baguwen

import (
	"github.com/ecodeclub/webook/internal/search/internal/repository"
	"github.com/ecodeclub/webook/internal/search/internal/repository/dao"
	"github.com/ecodeclub/webook/internal/search/internal/service"
	"github.com/ecodeclub/webook/internal/search/internal/web"
	"github.com/olivere/elastic/v7"
	"sync"
)

// Injectors from wire.go:

func InitModule(es *elastic.Client) (*Module, error) {
	searchSvc := InitSearchSvc(es)
	syncSvc := InitSyncSvc(es)
	handler := web.NewHandler(searchSvc)
	module := &Module{
		SearchSvc: searchSvc,
		SyncSvc:   syncSvc,
		Hdl:       handler,
	}
	return module, nil
}

// wire.go:

var daoOnce = sync.Once{}

func InitIndexOnce(es *elastic.Client) {
	daoOnce.Do(func() {
		err := dao.InitES(es)
		if err != nil {
			panic(err)
		}
	})
}

func InitRepo(es *elastic.Client) (repository.CaseRepo, repository.QuestionRepo, repository.QuestionSetRepo, repository.SkillRepo) {
	InitIndexOnce(es)
	questionDao := dao.NewQuestionDAO(es)
	caseDao := dao.NewCaseElasticDAO(es)
	questionSetDao := dao.NewQuestionSetDAO(es)
	skillDao := dao.NewSkillElasticDAO(es)
	questionRepo := repository.NewQuestionRepo(questionDao)
	caseRepo := repository.NewCaseRepo(caseDao)
	questionSetRepo := repository.NewQuestionSetRepo(questionSetDao)
	skillRepo := repository.NewSKillRepo(skillDao)
	return caseRepo, questionRepo, questionSetRepo, skillRepo
}

func InitSearchSvc(es *elastic.Client) service.SearchSvc {
	caseRepo, questionRepo, questionSetRepo, skillRepo := InitRepo(es)
	return service.NewSearchSvc(questionRepo, questionSetRepo, skillRepo, caseRepo)
}

func InitSyncSvc(es *elastic.Client) service.SyncSvc {
	caseRepo, questionRepo, questionSetRepo, skillRepo := InitRepo(es)
	return service.NewSyncSvc(questionRepo, questionSetRepo, skillRepo, caseRepo)
}

type SearchService = service.SearchSvc

type SyncService = service.SyncSvc

type Handler = web.Handler
