// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/ecodeclub/webook/internal/product"
	"github.com/ecodeclub/webook/internal/product/internal/service"
	"github.com/ecodeclub/webook/internal/product/internal/web"
	testioc "github.com/ecodeclub/webook/internal/test/ioc"
)

// Injectors from wire.go:

func InitService() service.Service {
	db := testioc.InitDB()
	serviceService := product.InitService(db)
	return serviceService
}

func InitHandler() (*web.Handler, error) {
	db := testioc.InitDB()
	mq := testioc.InitMQ()
	module, err := product.InitModule(db, mq)
	if err != nil {
		return nil, err
	}
	handler := module.Hdl
	return handler, nil
}
